name: Update Readme

on:
  push:
    branches:
      - master
  schedule:
    - cron: "45 21 * * *"
  workflow_dispatch:
    

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Get working copy
        uses: actions/checkout@master
        with:
          fetch-depth: 1                                                                 
      - name: Set up Python 3.9                               
        uses: actions/setup-python@v2                               
        with:                                 
          python-version: '3.9'                                                   
      - name: Install pypeteer and feedparser                             
        run: pip install feedparser pyppeteer
      - name: 🍳 Update README
        run: |
          cd ${GITHUB_WORKSPACE}/src/
          python run_blog_posts.py
          python run_screenshot.py
      - name: Deploy
        run: |
          git config user.name "${GITHUB_ACTOR}"
          git config user.email "${GITHUB_ACTOR}@users.noreply.github.com"
          git add .
          git commit -am "feat(auto generate): Updated medium profile posts and image"
          git push --all -f https://${{ secrets.GITHUB_TOKEN }}@github.com/${GITHUB_REPOSITORY}.git
